[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "pgres"
#version = "0.0.1"
dynamic = ["version"]
dependencies = [
]

[tool.setuptools_scm]


[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["src"]  # ["."] by default
include = ["pgres*"]  # ["*"] by default
exclude = ["pgres.tests*"]  # empty by default
namespaces = false  # true by default